### ISSUE TITLE
Lỗi trình bày bản đồ theo trạng thái trong phần bản đồ kiểm tra

### ISSUE THREAD

**Issue by giangttt** [duongnv1989/citywork#100]
Ứng dụng kiểm tra theo mô hình gFM trình bày theo layer đang bị lấy theo trình bày mặc định

**Comment by giangttt** [comment]
Vào tổ chức DT0000 trên app.citywork.vn để test lỗi phần ứng dụng Quản lý yêu cầu

**Comment by GiapCM** [comment]
Chinh xem debug xem cái lỗi này là ntn nhé

**Comment by GiapCM** [comment]
Cấu hình lại view cho phần kiểm tra có thêm trường trangthaixuly là được. Hiện giờ xử lý là alter lại view

**Comment by nguyendangcuong** [comment]
Các tổ chức đã chỉnh sửa view bằng tay đề nghị làm bằng tay. Không dùng phần mềm.
