### ISSUE TITLE
Phân quyền trong Biểu mẫu thu thập hoặc 1 cơ chế phân quyền khác

### ISSUE THREAD

**Issue by kdpmkien** [duongnv1989/citywork#101]
Cần cho phép truy tìm nhanh bằng từ khóa 1 thành viên (để với 1 tổ chức lớn cần có rất đông thành viên thì có thể nhanh chóng tìm thấy thành viên cần để cho phép thêm thành viên vào biểu mẫu)
Hiện giờ với 1 tổ chức đông thành viên thì việc add thêm thành viên vào biểu mẫu phải dò tìm rất mỏi mắt. VD:
![image](https://cloud.githubusercontent.com/assets/15392540/13905733/cc31c5b6-eefa-11e5-9f93-ec6c2eb032fc.png)

![image](https://cloud.githubusercontent.com/assets/15392540/13905898/fdf7fff8-eefe-11e5-8f99-0f3b2642f012.png)

**Comment by vietlv** [comment]
Chức năng filter thành viên đã có trên gcollector
Cho phép filter theo địa chỉ email, tên thành viên không phân biệt hoa thường
