### ISSUE TITLE
Lỗi phần quản trị

### ISSUE THREAD

**Issue by kdpmkien** [duongnv1989/citywork#103]
Trong tổ chức CN0002/quản trị/thành viên
tạo tài khoản 1 đằng nhưng ID hiển thị 1 nẻo

**Comment by duongnv1989** [comment]
Nhiều tài khoản bị thế hay chỉ một tài khoản vậy anh @kdpmkien ? Không thể phát hiện ra lỗi này

**Comment by kdpmkien** [comment]
Hôm trước bị thôi.
