### ISSUE TITLE
Cn0002 - lỗi không nhìn thấy bản ghi trên di động

### ISSUE THREAD

**Issue by kdpmkien** [duongnv1989/citywork#107]
1 số ID đã phân quyền là chủ sở hữu từ trước khi tạo biểu mẫu nhưng đến khi đăng nhập trên di động bằng ID đấy thì lại ko thấy bản ghi nào trong các biểu mẫu
ID: vunguyenhan; Pass: 123
ID: tienanh; pass: 123

**Comment by thamnguyen123** [comment]
Anh Kiên xóa dữ liệu offline đi rồi đồng bộ lại xem nhé.

**Comment by vudq** [comment]
Lỗi này thế nào, nếu không có lỗi thì close
