### ISSUE TITLE
Cn0002 - lỗi xóa thành viên bên Gsever nhưng bên gcolector vẫn còn

### ISSUE THREAD

**Issue by kdpmkien** [duongnv1989/citywork#108]
(tienanh.pvcth@gmail.com )
![image](https://cloud.githubusercontent.com/assets/15392540/13915407/18ade33e-ef87-11e5-99aa-383e907c3543.png)

**Comment by duongnv1989** [comment]
Đề nghị theo comment trong issuse này: https://github.com/duongnv1989/citywork/issues/113
