### ISSUE TITLE
Phần quản lý Thu thập trên web

### ISSUE THREAD

**Issue by kdpmkien** [duongnv1989/citywork#110]
Cần cho phép tìm kiếm nhanh biểu mẫu. hiện tại mà có nhiều biểu mẫu tìm rất khó khăn
![image](https://cloud.githubusercontent.com/assets/15392540/13947870/7d545f84-f04f-11e5-8c3b-aba8ccec4fc3.png)

**Comment by nguyendangcuong** [comment]
Chỗ text mờ (Gõ vào để tìm biểu mẫu) gõ vào đó để tìm biểu mẫu.
