### ISSUE TITLE
Lỗi xóa tài khoản

### ISSUE THREAD

**Issue by thoathoa91** [duongnv1989/citywork#113]
Quản trị tổ chức xóa tài khoản thành viên, thêm lại nhưng báo lỗi. Vì thực tế tài khoản đó vẫn còn trong admin -csdl  portal. Nên muốn xóa thì phải xóa ở 2 nơi
Yêu cầu: nếu tài khoản đó chỉ ở 1 tổ chức thì khi quản trị xóa thì xóa luôn trong hệ thồng, còn nếu tài khoản đó có trong tổ chức khác thì chỉ cho xóa khỏi tổ chức hiện tại. có cơ chế thông báo cho ng dùng biết!

**Comment by duongnv1989** [comment]
- Theo cơ chế hiện tại gCollector, xóa tài khoản chỉ xóa khỏi tổ chức, không xóa User. Khi tạo user, nếu kiếm tra tồn tại Email, người dùng sẽ thêm vào tổ chức (cơ chế một người dùng nhiều tổ chức)
- Đề nghị nếu muốn cập nhật, hay xóa tài khoản đều phải vào giao diện quản trị tổ chức làm. Không làm trong tài khoản Admin của mojo

**Comment by nguyendangcuong** [comment]
"Theo cơ chế hiện tại gCollector, xóa tài khoản chỉ xóa khỏi tổ chức, không xóa User. Khi tạo user, nếu kiếm tra tồn tại Email, người dùng sẽ thêm vào tổ chức (cơ chế một người dùng nhiều tổ chức)"
-> Citywork cơ chế hiện tại một email chỉ ở một tổ chức. 
Đảm bảo khi tạo một người dùng đã tồn tại email rồi thì thông báo - và không cho lưu trữ.
Trường hợp họ xóa người dùng đó đi -> sau đó tạo lại sẽ không tạo được phải liên hệ để mình hỗ trợ việc tạo tài khoản này.
