### ISSUE TITLE
Kiểm tra chức năng Mở rộng đối tượng trong phần công cụ biên tập nâng cao

### ISSUE THREAD

**Issue by ThuyPT05** [duongnv1989/citywork#118]

**Comment by ThuyPT05** [comment]
![loi](https://cloud.githubusercontent.com/assets/17447136/14070621/c6cf0164-f4d2-11e5-9e6d-4a3a3021953e.png)

**Comment by duongnv1989** [comment]
OK

**Comment by duongnv1989** [comment]
Chú ý: Có thể phải dùng thêm chức năng đảo chiều đường để extend chuẩn
