### ISSUE TITLE
Cn0009 - Lỗi không hiển thị giá trị trong đơn vị quản lý

### ISSUE THREAD

**Issue by kdpmkien** [duongnv1989/citywork#119]
dù trong danh mục đơn vị quản lý đã tạo 1 đơn ị quản lý rồi mà khi phận thông tin thuộc tính vẫn không hiển thị giá trị đấy ra để lựa chọn nhập
![image](https://cloud.githubusercontent.com/assets/15392540/14097820/1012b912-f5a8-11e5-835f-05d688094ff2.png)
![image](https://cloud.githubusercontent.com/assets/15392540/14097903/fb9dd7ae-f5a8-11e5-9c49-09a2061e1835.png)

**Comment by GiapCM** [comment]
Đây là chức năng cấu hình của gServer không phải chức năng của gFM

**Comment by duongnv1989** [comment]
Anh @kdpmkien  tra lại, bảng thuộc tính a mở ở trên là bảng **cn0009_tbldmdonviquanly** nằm trong chủ đề CN0009_DanhMuc, còn giá trị đơn vị quản lý trong đối tượng Trạm bơm lại cấu hình vào bảng **CN0009_gfmdmdonviquanly** thuộc chủ đề Quản lý tài sản/Danh mục (bảng này không có dữ liệu)
