### ISSUE TITLE
cn0009 - lỗi trình bày bản đồ

### ISSUE THREAD

**Issue by kdpmkien** [duongnv1989/citywork#121]
tạo đường ống nhánh bị lẫn sang ống ttpp
![image](https://cloud.githubusercontent.com/assets/15392540/14195906/3d96629c-f7e9-11e5-862d-9b6a937958ed.png)

**Comment by thoathoa91** [comment]
Chỗ mục Nhánh dịch vụ: anh chọn ống nhánh. Anh đang chọn là TTPP thì sai là đúng rồi!

**Comment by kdpmkien** [comment]
sao ko để mặc định nó là nhánh dịch vụ đi nhỉ

**Comment by thoathoa91** [comment]
Cái này nó lấy theo thứ tự, Em đã kéo cục mảng dịch vụ lên trên, anh F5 lại nhé!
