### ISSUE TITLE
web - xem lịch sử thuê bao bị lỗi

### ISSUE THREAD

**Issue by nguyendangcuong** [duongnv1989/citywork#122]
Xem lịch sử thuê bao bị lỗi: http://abc.vn..../settings/organizations/55d54638926b3f101fe60f77/subscriptionhistory
....
Cannot read property 'orgname' of undefined

**Comment by duongnv1989** [comment]
Link gì đây anh Cường?

**Comment by vietlv** [comment]
Đã fix lỗi undefined, lỗi này phát sinh khi không có lịch sử gia hạn gói của tổ chức, không lấy đủ thông tin để hiển thị
