### ISSUE TITLE
lỗi đăng nhập trên citywork.vn

### ISSUE THREAD

**Issue by kdpmkien** [duongnv1989/citywork#123]
các đăng nhập trên bằng citywork.vn đều bị chuyển sang link này và không đăng nhập được
http://app.cloudgis.vn/Secure/Login.aspx?returnurl=http%3a%2f%2fapp.cloudgis.vn%2fapps.aspx
![image](https://cloud.githubusercontent.com/assets/15392540/14236870/1c366e8a-fa46-11e5-813e-6126cb18f0f1.png)

**Comment by vietlv** [comment]
Đây là cloudgis mà anh, có phải citywork đâu?

**Comment by nguyendangcuong** [comment]
Okie rồi.
