### ISSUE TITLE
Web -  Xem thông tin tài sản

### ISSUE THREAD

**Issue by nguyendangcuong** [duongnv1989/citywork#125]
- Thay biểu tượng xem thông tin tài sản chữ i -> 
![image](https://cloud.githubusercontent.com/assets/8967627/14241391/765a102c-fa75-11e5-8b93-5e3fc56ee4ce.png) nhờ Quân design.
- Trong lớp bản đồ bổ sung thêm cấu hình mở rộng (gần giống xem thông tin liên kết) với tên cấu hình: "xem thông tin tài sản" checkbox và ô text nhập nhãn. Khi info một tài sản click vào đó gọi form quản lý thiết bị (thông tin tài sản lên).

**Comment by duongnv1989** [comment]
OK
