### ISSUE TITLE
Giúp anh thiết lập lại tài khoản này bị lỗi với

### ISSUE THREAD

**Issue by kdpmkien** [duongnv1989/citywork#126]
CN0009 ID: lemainuocsach
mail: lemainuocsach@gmail.com
pass: 123

![image](https://cloud.githubusercontent.com/assets/15392540/14302366/9207da94-fbd2-11e5-9500-401637f3360c.png)

![image](https://cloud.githubusercontent.com/assets/15392540/14302358/8639c43e-fbd2-11e5-8043-f49e8dfe4f8f.png)

![image](https://cloud.githubusercontent.com/assets/15392540/14302346/71567684-fbd2-11e5-88ad-373d73106ef3.png)

**Comment by vietlv** [comment]
Đã fix cho user này, mật khẩu là 123

**Comment by duongnv1989** [comment]
Anh Kiên chú ý khi copy địa chỉ Email nhé, hay có ký tự trắng.

**Comment by nguyendangcuong** [comment]
Nếu có ký tự trắng trước hoặc sau? mình bỏ đi không lưu trữ vào.
