### ISSUE TITLE
Lỗi chạy lại topology

### ISSUE THREAD

**Issue by OanhLee** [duongnv1989/citywork#129]
Tính năng này trả ra kết quả không đúng (Sau khi sửa lại lỗi, dùng tính năng này lỗi vẫn trả ra)

**Comment by BuiGiang** [comment]
Đề nghị bên phần mềm SỬA NGAY LỖI NÀY, nếu không thì không thể nào kiểm soát và đánh giá được dữ liệu và không thể nào kết thúc được công việc. Vì các tuyến ống không đúng mà đã làm các nhánh dịch vụ thì khi sửa lại tuyến ống, các nhánh dịch vụ cũng phải sửa theo. Điều đó sẽ rất không khoa học.

**Comment by duongnv1989** [comment]
@chinhls chinh xem những cái issuse nào mà sửa rồi hay có ý kiến gì thì comment lại?
