### ISSUE TITLE
Công cụ mở rộng đối tượng

### ISSUE THREAD

**Issue by OanhLee** [duongnv1989/citywork#130]
Muốn bắn 1 đường vào 1 đường khác, công cụ này gây mất thời gian cho người dùng. Đường vẽ thêm được sinh ra từ điểm cuối của đường bắn -> Người dùng phải đảo chiều lại đường nếu không phải là điểm cuối -> Không linh hoạt)
Đề xuất: Đường vẽ thêm nên lấy từ điểm gần nhất của đường bắn so với đối tượng đường đã chọn
[![morongduong](https://cloud.githubusercontent.com/assets/18326213/14373583/c7efe2ce-fd75-11e5-8111-cd8c4edec15f.jpg)
](url)

**Comment by BuiGiang** [comment]
Đồng ý với OanhLee, ý này rất cần thiết vì chỉ cần người dùng sơ ý khi sử dụng công cụ này thì rất dễ bị lỗi tự chồng đè.

**Comment by duongnv1989** [comment]
OK. Extend đối với đầu của đường mà người dùng chọn
