### ISSUE TITLE
Công cụ chồng đè

### ISSUE THREAD

**Issue by OanhLee** [duongnv1989/citywork#131]
Bổ sung công cụ kiểm tra quan hệ chồng đè của đối tượng

**Comment by BuiGiang** [comment]
Đây là một trong những công cụ tối thiểu mình phải có. Nó ảnh hưởng lớn đến thống kê. Các em sắp xếp thời gian để bổ sung nhé!

**Comment by OanhLee** [comment]
A bổ sung cho bọn e chồng đè điểm và đường trước nhé
