### ISSUE TITLE
Bổ sung công cụ copy/cut, Paste và move đối tượng

### ISSUE THREAD

**Issue by BuiGiang** [duongnv1989/citywork#136]
Nên bổ sung công cụ copy/cut, Paste hoặc copy parallel đối tượng "từ lớp này sang lớp khác", sẽ hữu ích trong trường hợp:
+ Số hóa các đường song song với một đối tượng hình tuyến
+ Số hóa nhầm lớp.

**Comment by duongnv1989** [comment]
OK

**Comment by duongnv1989** [comment]
Đã hỗ trợ cho phép copy từ hai lớp  khác nhau và cũng kiểu không gian (point-point, line-line, polygon-polygon)
