### ISSUE TITLE
Sửa gấp! lỗi xem thông tin chi tiết trong phần quản lý yêu cầu

### ISSUE THREAD

**Issue by duclv109** [duongnv1989/citywork#140]
Các phiếu yêu cầu xem thông tin chi tiết bị lỗi, thông tin trong biểu mẫu thì đầy đủ mà thông tin trong yêu cầu thì trắng.

Không đưa các thông tin link, tài khoản đăng nhập lên đây

**Comment by GiapCM** [comment]
Do thông tin cấu hình thông tin cho nội dung 1 và nội dung 2 như thế

**Comment by duclv109** [comment]
Cái này bên Dương xử lý giúp phần đồng bộ từ biểu mẫu sang gserver. Sáng thứ 5 thử nghiệm ở Bắc Ninh
