### ISSUE TITLE
lỗi không nhận x; y đại diện của đối tượng nhà máy nước

### ISSUE THREAD

**Issue by kdpmkien** [duongnv1989/citywork#141]
![image](https://cloud.githubusercontent.com/assets/15392540/14455425/a2acd0a6-00c9-11e6-8d94-3374b88cd5f7.png)

**Comment by kdpmkien** [comment]
tổ chức CN0009 nhé

**Comment by duongnv1989** [comment]
Anh bỏ cấu hình hiển thị trường xDaiDien và yDaiDien trong các biểu mẫu đi nhé. Sau đó sửa lại dữ liệu không gian => hai trường xDaiDien, yDaiDien sẽ tự động cập nhật theo dữ liệu không gian
