### ISSUE TITLE
web-Lỗi stop dịch vụ? workoder

### ISSUE THREAD

**Issue by nguyendangcuong** [duongnv1989/citywork#144]
sáng 13/04 chiếu sáng không giao việc được -> báo sang mình mới biết? khắc phục lỗi nếu bị lỗi thì tự khởi động lại dịch vụ.

**Comment by vietlv** [comment]
Em đã kiểm tra và khắc phục ngay, lỗi này do trong 1 view trong cổng Portal của thu thập bị lỗi đã fix và khởi động lại portal
