### ISSUE TITLE
Zoom to lỗi topology

### ISSUE THREAD

**Issue by OanhLee** [duongnv1989/citywork#146]
Click đúp vào danh sách đối tượng bị lỗi, kết quả hiển thị màn hình không đúng vị trí bị lỗi -> Người dùng mất thời gian tìm kiếm vị trí bị lỗi.
Đề xuất: Click đúp đối tượng phải zoom to đến vị trí bị lỗi
![13041](https://cloud.githubusercontent.com/assets/18326213/14482317/a5268c54-0165-11e6-852e-95f8c34efabc.jpg)

**Comment by duongnv1989** [comment]
Hiện tại zoom theo vùng bao của đối tượng (đối tượng đường nên vùng bao sẽ rộng). 
Riêng với đề xuất "Click đúp đối tượng phải zoom to đến vị trí bị lỗi" rất khó vì trên một đối tượng đường có thể có nhiều lỗi, không biết mà zoom tới thằng nào

**Comment by OanhLee** [comment]
Thay vì zoom theo vùng bao đối tượng, mình sẽ zoom theo điểm bị lỗi (Thực tế lỗi sinh ra đang được hiển thị theo điểm ngoài lỗi chồng đè). Như vậy zoom to đến vị trí lỗi sẽ chính xác hơn
