### ISSUE TITLE
Kiểm tra phần đồng bộ từ biểu mẫu kiểm tra lên quản lý yêu cầu

### ISSUE THREAD

**Issue by duclv109** [duongnv1989/citywork#156]
Các trường được thiết kế trong Mục không đồng bộ được dữ liệu lên lớp kiểm tra 

Hệ thống Lưới điện cao thế Miền Bắc app.citywork
![2016-04-19_11-00-59](https://cloud.githubusercontent.com/assets/16813946/14627495/3dcb134a-061f-11e6-8ea1-afdab5b4d613.png)
![2016-04-19_11-03-50](https://cloud.githubusercontent.com/assets/16813946/14627496/3dcc4eae-061f-11e6-8e7f-069ab87ea474.png)

**Comment by duclv109** [comment]
Việc này cần ưu tiên sửa vì trong giai đoạn này đang thử nghiệm để công ty đánh giá hệ thống

**Comment by vietlv** [comment]
Vừa cập nhật lại dịch vụ với trường hợp có Mục trong biểu mẫu, đức xem lại nhé, đã test
