### ISSUE TITLE
Lỗi giao diện sửa thông tin phụ kiện

### ISSUE THREAD

**Issue by thoathoa91** [duongnv1989/citywork#160]
Giao diện khi nháy đúp ở bảng thuộc tính rồi sửa khác giao diện khi chọn phụ kiến nhấn nút sửa
![x2](https://cloud.githubusercontent.com/assets/12489133/14669475/3f112768-0713-11e6-9874-48123c7be59b.png)
![x3](https://cloud.githubusercontent.com/assets/12489133/14669476/3f42ad9c-0713-11e6-9a35-4fb5d161b6a8.png)

**Comment by jakychan** [comment]
Sửa xong!
