### ISSUE TITLE
Anh xem xử lý cho em cái lỗi bản đồ này vơi: Cứ Zoom tới mức này thì nó lại trắng mất 1 vùng

### ISSUE THREAD

**Issue by kientrangis** [duongnv1989/citywork#162]
Anh xem xử lý cho em cái lỗi bản đồ này với: Cứ Zoom tới mức này thì nó lại trắng mất 1 vùng
![loibando](https://cloud.githubusercontent.com/assets/17466437/14702480/e7dd54fe-07d4-11e6-938d-bb6f9edc3353.jpg)

**Comment by duongnv1989** [comment]
Em Ctrl + F5 lại trình duyệt nhé. Anh cập nhật mới rồi
