### ISSUE TITLE
Lỗi hiện thị danh sách chủng loại tài sản

### ISSUE THREAD

**Issue by thoathoa91** [duongnv1989/citywork#164]
Chủng loại tài sản hiện thị có 25 chủng loại/ trang.
![x4](https://cloud.githubusercontent.com/assets/12489133/14758572/d247c4e8-092e-11e6-8a99-0a10c0005d35.png)
![x5](https://cloud.githubusercontent.com/assets/12489133/14758571/d247a3dc-092e-11e6-9485-3e70ee9b9c3a.png)

**Comment by jakychan** [comment]
Hoàn thành
