### ISSUE TITLE
mobile - Xóa điều kiện tìm kiếm

### ISSUE THREAD

**Issue by nguyendangcuong** [duongnv1989/citywork#177]
sau khi tìm kiếm 
-> bấm sắp xếp thì bị xóa điều kiện tìm kiếm.
-> bấm vào xem một bản ghi - khi quay lại xóa điều kiện tìm kiếm

**Comment by vietlv** [comment]
Em vừa đẩy lên store, chiều nay 04/05/2016 sẽ được cập nhật
