### ISSUE TITLE
Lỗi xem tệp đính kèm

### ISSUE THREAD

**Issue by kdpmkien** [duongnv1989/citywork#181]
Lỗi xem tệp đính kèm khi infor thông tin tài sản
![untitled](https://cloud.githubusercontent.com/assets/15392540/15034690/5151beca-12a2-11e6-863f-12e41b6b567c.png)

**Comment by duongnv1989** [comment]
Cái này cần xem lại cấu hình cũng như giá trị của trường đính kèm.

**Comment by giangttt** [comment]
Nguyên nhân là do trường tài nguyên số đang bị gán sai đường dẫn. Gán lại giá trị trường taiNguyenSO = null là được
