### ISSUE TITLE
Bổ sung: Khi thêm mới bảng tài sản (gfmcauhinh) thì có chọn hệ tọa độ

### ISSUE THREAD

**Issue by thoathoa91** [duongnv1989/citywork#193]
Hiện tại khi thêm các bảng tài sản là WGS84- nhưng k phải lớp nào cũng hệ tọa độ đó!. Tham khảo gServer

**Comment by GiapCM** [comment]
Muốn thực hiện việc này chỉ cần tạo thêm các tài sản mẫu có các hệ tọa độ tương ứng
