### ISSUE TITLE
Lỗi thêm thành viên vào biểu mẫu

### ISSUE THREAD

**Issue by thoathoa91** [duongnv1989/citywork#195]
1. Thêm thành viên - quyền Quản lý -> nhưng kq lại là Xem dữ liệu (Không đồng nhất giữa chọn quyền và lưu lại)
 2. Có khả năng sửa lại quyền thành viên trong biểu mẫu (Bổ sung thêm nút sửa)

**Comment by GiapCM** [comment]
Đây là nghiệp vụ khi tạo ra biểu mẫu kiểm tra từ danh sách tài sản cần kiểm tra.
Sao lại chuyển thành bug thế
