### ISSUE TITLE
Lỗi cập nhật thông tin địa điểm Tiếp nhận yêu cầu

### ISSUE THREAD

**Issue by thoathoa91** [duongnv1989/citywork#205]
Chỉ điền thông tin địa điểm lần đầu tiên khi kích vị trí trên bản đồ, chọn vị trí khác thì k tự động điền lại
![x12](https://cloud.githubusercontent.com/assets/12489133/15698365/1225b43e-27ee-11e6-9dc4-8f78c5969cc3.png)

**Comment by nguyendangcuong** [comment]
Đang để logic như vậy. Nếu ô địa điểm có text rồi thì không bind lại dữ liệu nữa.
