### ISSUE TITLE
Lỗi xem công việc từ đối tượng kiểm tra

### ISSUE THREAD

**Issue by thamnguyen123** [duongnv1989/citywork#209]
Chỉ thêm mới một công việc cho 1 kiểm tra nhưng khi xem thông tin công việc  thì hiển thị 2 công việc có thông tin giống hệt nhau ( bị lỗi đối với các kiểm tra được đồng bộ từ thiết bị di động)

**Comment by nguyendangcuong** [comment]
Giáp fix cái này luôn nhé. Tưởng hết lỗi này rồi!
Fix xong vào dữ liệu xóa hộ những công việc sao chép ra để người dùng không thấy.

Thank!
