### ISSUE TITLE
Lỗi cập nhật tiêu đề biểu mẫu trong modul kiểm tra của gEAM

### ISSUE THREAD

**Issue by giangttt** [duongnv1989/citywork#213]
Cập nhật lại tiêu đề biểu mẫu thì trên di động các bản ghi bị chuyển thành "Không tiêu đề" mặc dù cấu hình trường tiêu đề đã thay đổi

**Comment by vietlv** [comment]
Em đã kiểm tra lại và vẫn thấy chạy bình thường, chị sau khi cập nhật lại trường tiêu đề thì trên mobile cần đồng bộ lại sẽ hiển thị được tiêu đề.
Chị chạy lại xem có được không? Nếu chưa được thì chị comment lại tài khoản đăng nhập, tên biểu mẫu cụ thể để kiểm tra lại

**Comment by giangttt** [comment]
Sửa biểu mẫu trên gcolector thì không vấn đề gì. nhưng sửa trên gserver và cập nhật lại biểu mẫu thì bị lỗi trên. Phải vào quản lý biểu mẫu trên gsever và đẩy lại dữ liệu mới được

**Comment by vietlv** [comment]
Bên anh Giáp, anh Hữu kiểm tra lại khi lưu lại biểu mẫu ở bên module kiểm tra có thể do key của anh đã bị cập nhật mới do đó trường tiều đề không hiển thị được nữa, bên anh cần xem lại code giống phần cập nhật biểu mẫu như trong geditor giữ nguyên các key (trong các element)
