### ISSUE TITLE
Yêu cầu các thông tin trong ĐƯờng dây nóng điều chỉnh được cho mỗi ngành (chiếu sáng, cấp nước, đường bộ,...)

### ISSUE THREAD

**Issue by thoathoa91** [duongnv1989/citywork#214]
![yeuccau](https://cloud.githubusercontent.com/assets/12489133/16334234/ef72d09a-3a29-11e6-8d68-fdbf9759c490.png)

**Comment by thoathoa91** [comment]
Mẫu này đang cho bên Cấp nước, ngành khác giao điện ko phù hợp

**Comment by nguyendangcuong** [comment]
E dùng mẫu này: gfmcallcenter.aspx

**Comment by thoathoa91** [comment]
Ví dụ lúc tạo tổ chức có chọn ngành thì giao diện nó ăn theo. chứ bjo toàn
thấy thông tin bên cấp nước . ở đường dây nóng

Vào Thứ Sáu, ngày 24 tháng 6 năm 2016, nguyendangcuong <
notifications@github.com> đã viết:

> E dùng mẫu này: gfmcallcenter.aspx
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/duongnv1989/citywork/issues/214#issuecomment-228306892>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AL6Rrf5gqlfXYqt5PrRwRsoqdb4gE8TRks5qO6rHgaJpZM4I9nSK>
> .
>


-- 
Được gửi từ Gmail Mobile
