### ISSUE TITLE
Lỗi trường tính toán trên mobile bên govone

### ISSUE THREAD

**Issue by votahuy** [duongnv1989/citywork#224]
Khi biểu mẫu có trường tính toán nhập liệu không thay đổi trên govone
(Tổ chức db0004)

**Comment by thoathoa91** [comment]
anh xem đã có phép toán (trường a +- trường b) chưa?. Hay chỉ mới kéo
trường tính toán vào???






---
*Nguyễn Thị Thoa/ Miss Thoa*

Mobile: +84 1666-762-854
------------------------------------------------------------
Công ty Cổ phần Công nghệ Thông tin Địa lý eK
eK Geo-Information Technology Joint Stock Company (*eKGIS.,JSC*)


2016-07-11 16:12 GMT+07:00 votahuy <notifications@github.com>:
