### ISSUE TITLE
Lỗi đăng ký bảng tài sản gfmcauhinh

### ISSUE THREAD

**Issue by thoathoa91** [duongnv1989/citywork#228]
Khi thêm mới 1 tài sản, chọn kiểu không gian (điểm, đg, vùng) nhưng sang gmanager thì toàn bộ là bảng danh mục
Khi sửa lớp dữ liệu bên gmanager thì :-1: 
+ bảng đó đã check là lớp không gian nhưng mục kiểu không gian ko có
+ Mục tên đầy đủ là tên của bảng mẫu + n lần từ "Sao chép" . tạo thứ 3 thì sau đó có 3 tên sao chép...
Tổ chức ví dụ: dl0004/******

**Comment by GiapCM** [comment]
Đã vào kiểm tra thử vẫn thấy chạy bình thường.
Cho một ví dụ cụ thể lỗi nhé

**Comment by thoathoa91** [comment]
cai nay e chi cho c Cong^ thay roi. co loi nhe k phai bthg dau!






---
*Nguyễn Thị Thoa/ Miss Thoa*

Mobile: +84 1666-762-854
------------------------------------------------------------
Công ty Cổ phần Công nghệ Thông tin Địa lý eK
eK Geo-Information Technology Joint Stock Company (*eKGIS.,JSC*)


2016-07-20 8:25 GMT+07:00 GiapCM <notifications@github.com>:
