### ISSUE TITLE
Mobile - Checkin

### ISSUE THREAD

**Issue by nguyendangcuong** [duongnv1989/citywork#235]
Trong phần checkin:
+ Trên di động xem bản đồ không thấy có marker
+ Trên di động khi xem dữ liệu -> trên tiêu đề có tên biểu mẫu. -> Vào phần giám sát tiêu đề vẫn lấy tên biểu mẫu
+ Trên web không gửi được thông báo

Nút thêm mới:
+ Chỉ có biểu mẫu tag: thu thập hoặc kiểm tra mới có nút thêm mới
+ Khi có nút thêm mới thì bấn vào các vùng khác vẫn được chỉ bẩm vào nút thêm mới thì thêm mới. Vùng trống ngay cạnh nút thêm mới thì vào danh sách

**Comment by vietlv** [comment]
Phiên bản web và android đã được cập nhật sửa những lỗi ở trên
