### ISSUE TITLE
Yêu cầu: Không cho phép thiết bị (điện thoại. máy tính bảng) bật vị trí giả 

### ISSUE THREAD

**Issue by thoathoa91** [duongnv1989/citywork#248]
Ở bên Mobiwork có chặn nếu máy bật vị trí giả thì ko đăng nhập được vào phần mềm. Lúc đăng nhập có thông báo. Như thế ko cho nhân viên sử dụng các phần mềm hack vị trí (VD:Fake GPS)

**Comment by vudq** [comment]
Việt kiểm tra cái này rồi hướng dẫn Dương update.
