### ISSUE TITLE
Lỗi bản đồ offline không zoom được

### ISSUE THREAD

**Issue by dungmdc1987** [duongnv1989/citywork#249]
![screenshot_20160910-110940](https://cloud.githubusercontent.com/assets/17448538/18407858/47852af8-7747-11e6-8138-7340ce261343.png)

**Comment by vudq** [comment]
Dung cung cấp thêm thông tin, tất cả bản đồ ofline không zoom đc hay chỉ 1 bản đồ. Nếu chỉ 1 bản đồ thì bản đồ ấy ở đâu, Dương kiểm tra nội dung file offline (ChinhHĐ)

**Comment by thoathoa91** [comment]
Anh kiểm tra bản đồ offline của tổ chức thoát nước Hn (tn0001) (BĐ Vệ tinh quanh Hồ Bảy Mẫu)
Anh xem luôn cho e nhé, vì hnay đi triển khai rồi ạ
Tks các anh!

**Comment by nguyendangcuong** [comment]
Máy Dung giờ lại được rồi. Bật tắt ứng dụng, chuyển đổi bản đồ -> zoom đã khỏi lỗi.
