### ISSUE TITLE
Lỗi phân quyền ứng dụng

### ISSUE THREAD

**Issue by thamnguyen123** [duongnv1989/citywork#253]
Khi thêm mới thành viên vào tổ chức tự động trong phần phân quyền đã có các quyền vào ứng dụng, bản đồ( không biết quyền đang lấy từ tài khoản nào)

**Comment by duongnv1989** [comment]
Quyền gán cho Tổ chức (mỗi tổ chức tạo ra sẽ sinh ra role mã tổ chức)
