### ISSUE TITLE
gCollector mobile - hiển thị danh sách lớp bản đồ

### ISSUE THREAD

**Issue by nguyendangcuong** [duongnv1989/citywork#28]
- Hiện tại trên gcollector web -> cấu hình các lớp bản đồ mbtile và tile xyz.
Khi xuống mobile mới hiển thị các lớp bản đồ mbtile -> fix để hiển thị các lớp tile xyz để người dùng lựa chọn. Khi có mạng người dùng có thể xem được các bản đồ này.
- Khi xem bản đồ trên mobile, chọn chức năng định vị GPS chỉ pan đến vị trí GPS (Không zoom max - đã fix nhưng chưa thấy trên bản cập nhật)

**Comment by duongnv1989** [comment]
@vietlv: Việt xem issuse này sửa chưa?
