### ISSUE TITLE
Báo "Đối tượng đã tồn tại" khi thêm đối tượng mới

### ISSUE THREAD

**Issue by thoathoa91** [duongnv1989/citywork#32]
Chiếu sáng: khi thêm mới đối tượng mà có thông tin bắt buộc , duy nhất trùng với đối tượng khác thì báo để ng dùng biết
Ví dụ: Khi thêm mới tủ điện (Tủ điện yêu cầu nhập mã tủ, và mã tủ là trường duy nhất). Nếu người dùng nhập mã tủ trùng với một tủ đã có sẵn thì khi lưu không báo lỗi gì, người dùng nghĩ là lưu được.

**Comment by duongnv1989** [comment]
Hệ thống hiện tại chưa thể bắt được trường hợp lỗi này. Để đảm bảo dữ liệu luôn duy nhất có thể vào cấu hình của trường dữ liệu lựa chọn giá trị duy nhất cho trường đó
