### ISSUE TITLE
mobile - Thông tin công việc

### ISSUE THREAD

**Issue by nguyendangcuong** [duongnv1989/citywork#59]
- Trong danh sách công việc trên mobile --> Cần hỗ trợ hiển thị số lượng công việc.
Hiện tại hiển thị danh sách công việc nhưng người dùng không biết có bao nhiêu công việc.
- Xem vị trí công việc (Bấm vào quả cầu) --> Báo lỗi google map api --> Cập nhật lại thư viện
The Staticmap API V1 has been deprecated as of 2009.....

**Comment by vietlv** [comment]
Đã fix
