### ISSUE TITLE
Lỗi giao diện bản đồ Kiểm tra.

### ISSUE THREAD

**Issue by thoathoa91** [duongnv1989/citywork#61]
Ấn vào xem toàn bản đồ thì không có mũi tên chuyển lại giao diện cũ
![24-02-2016 8-47-47 sa](https://cloud.githubusercontent.com/assets/12489133/13273065/615516a2-dad3-11e5-8d33-cfd1e57e27da.jpg)

**Comment by duongnv1989** [comment]
@HuuTV  đã sửa

**Comment by duongnv1989** [comment]
@HuuTV  đã sửa
