### ISSUE TITLE
mobile - Lỗi font chữ

### ISSUE THREAD

**Issue by nguyendangcuong** [duongnv1989/citywork#67]
Dữ liệu sau khi nhập trên mobile đồng bộ vệ hiện tại thường xuyên lỗi font chữ.
![image](https://cloud.githubusercontent.com/assets/8967627/13312364/927b6c04-dbc8-11e5-9843-73fdca0bcbe8.png)

**Comment by vietlv** [comment]
Đã cập nhật sửa lỗi và cập nhật lên citywork
