### ISSUE TITLE
Citywork - di động

### ISSUE THREAD

**Issue by kdpmkien** [duongnv1989/citywork#69]
- không tiến hành giao việc trên di động được
- Quay lại trong công việc trên di động lỗi

**Comment by vietlv** [comment]
Phiên bản hiện tại chỉ mới xem được thông tin và cập nhật công việc, muốn tiến hành giao việc thì cần thời gian để nâng cấp hoàn thiện

**Comment by vietlv** [comment]
Đã chỉnh sửa nhưng chưa cập nhật lên store, cuối tuần này sẽ cập nhật lên
