### ISSUE TITLE
Tìm kiếm trong phần kiểm tra mạng lưới.

### ISSUE THREAD

**Issue by thamnguyen123** [duongnv1989/citywork#73]
Người dùng trên công ty cấp nước Vĩnh Phúc đề xuất là phần tìm kiếm trong kiểm tra mạng lưới nhìn rối mắt quá.
![l i](https://cloud.githubusercontent.com/assets/15812186/13455621/294d0e18-e091-11e5-9a15-287f3055bd7e.PNG)

**Comment by GiapCM** [comment]
Đã điều chỉnh lại giao diện cho hợp lý hơn một chút. Mọi người xem và cho thêm ý kiến nếu có để điều chỉnh.
