### ISSUE TITLE
gServer - Quản trị người dùng

### ISSUE THREAD

**Issue by nguyendangcuong** [duongnv1989/citywork#74]
Hỗ trợ khả năng thiết lập mật khẩu cho người dùng. Rất nhiều người dùng quên mật khẩu -> người quản trị có thể thiết lập được mật khẩu lại cho người dùng.

**Comment by duongnv1989** [comment]
Người quản trị ở đây có hai khái niệm:
- Quản trị hệ thống Admin
- Quản trị tổ chức
A @nguyendangcuong cho em ý kiến này

**Comment by duclv109** [comment]
Cái này quản trị tổ chức là chuẩn nhất. Nhưng với điều kiện mỗi tổ chức một admin thôi

**Comment by duongnv1989** [comment]
Mọi thứ liên quan đến tổ chức đều dưa về giao diện quản trị tổ chức, người quản trị tổ chức được phép  sửa mật khẩu người dùng
