### ISSUE TITLE
Lỗi chức năng Khai thác ở ứng dụng Khai thác bản đồ tổ chức chiếu sáng

### ISSUE THREAD

**Issue by thoathoa91** [duongnv1989/citywork#83]
Anh Dương xem giúp em, trước làm cho Hapulico (cs0000) có fix sẵn gì không mà tổ chức cs0001 này không chạy nhé

**Comment by duongnv1989** [comment]
@thoathoa91 : Thoa cần note lại những yêu cầu khi sử dụng chức năng này:
- Yêu cầu về tên bảng cần phải có
- Yêu cầu về các trường thuộc tính 
- Yêu cầu về kiểu dữ liệu thuộc tính
