### ISSUE TITLE
Lỗi Tổng hợp dữ liệu tổ chức DT0001

### ISSUE THREAD

**Issue by ThuyPT05** [duongnv1989/citywork#86]
Khi đổ dữ liệu vào không tự động tổng hợp số liệu

**Comment by duongnv1989** [comment]
@ThuyPT05: Em mô tả rõ hơn, ở module nào

**Comment by ThuyPT05** [comment]
Ở module cây xanh, em thêm mới cây xanh nhưng lại không tổng hợp dữ liệu ( loại cây, tên cây, hiện trạng,..)

**Comment by nguyendangcuong** [comment]
Thắm vào thiết lập job để nó chạy. Cuối ngày chạy một lần để tổng hợp dữ liệu.

**Comment by thamnguyen123** [comment]
Em đã thiết lập job. Tổng hợp chạy ok rồi nhé
