### ISSUE TITLE
Lỗi tự động cấu hình danh mục hệ thống vào tài sản khi đã có danh mục

### ISSUE THREAD

**Issue by thoathoa91** [duongnv1989/citywork#87]
Khi thêm tài sản, nếu đã có các danh mục hệ thống (đơn vị quản lý, hiện trạng sd, tình trạng ts,..) thì sẽ tự động được cấu hình vào bảng tài sản.
Nhưng bjo lại k thấy!

**Comment by GiapCM** [comment]
Nếu chưa thấy được cấu hình thì kiểm tra lại bảng tài sản mẫu xem đã được cấu hình chưa. Nếu chưa thì cầu hình lại là được
