### ISSUE TITLE
Lỗi xuất bản đồ ra tệp AutoCad

### ISSUE THREAD

**Issue by ThuyPT05** [duongnv1989/citywork#89]
Phần mềm báo vẫn xuất được file, nhưng khi mở lên không thấy gì. 
![loi](https://cloud.githubusercontent.com/assets/17447136/13627504/6428d7bc-e5fd-11e5-96c6-b6d1af2b2fc0.png)

**Comment by duongnv1989** [comment]
Thiếu file template (trailer.dxf) trên hệ thống
