### ISSUE TITLE
gCollector - Xem chi tiết bản ghi

### ISSUE THREAD

**Issue by nguyendangcuong** [duongnv1989/citywork#90]
Khi xem chi tiết một bản ghi. Nếu bản ghi đó đính vào công việc, xem công việc liên quan thì giao diện hiển thị bị lặp lại.
![image](https://cloud.githubusercontent.com/assets/8967627/13662309/11672c98-e6cc-11e5-8368-d00ccaf5e6fe.png)

**Comment by vietlv** [comment]
Lỗi do bị copy code render html nhiều lần, đã fix
