### ISSUE TITLE
Mobile - Lỗi back từ phần gửi mail

### ISSUE THREAD

**Issue by nguyendangcuong** [duongnv1989/citywork#91]
Khi xem một công việc -> Bấm phản hồi -> Bấm váo thiết lập người gửi email. Sau đó không back lại được.
![image](https://cloud.githubusercontent.com/assets/8967627/13664631/02368e80-e6db-11e5-8d42-1aef68442695.png)

**Comment by vietlv** [comment]
Em vừa sửa lỗi này nhưng chưa up lên store, sẽ cập nhật lên store sau
