### ISSUE TITLE
Ghi chỉ số - Bỏ 2 nút Nhập dữ liệu + Tạo biểu mẫu khi mở biểu mẫu ghi chỉ số

### ISSUE THREAD

**Issue by thoathoa91** [duongnv1989/citywork#96]
![bonut](https://cloud.githubusercontent.com/assets/12489133/13766144/f07626b4-ea91-11e5-9f6a-1a63d159ec0e.jpg)

**Comment by vietlv** [comment]
Đã bỏ 2 nút trên khỏi giao diện
