### ISSUE TITLE
Khi nhập dữ liệu từ file excel đại đa số(99.9%) dòng bắt đầu dữ liệu là dòng thứ 2. Chỉnh lại từ 1>2!

### ISSUE THREAD

**Issue by thoathoa91** [duongnv1989/citywork#99]
![dong](https://cloud.githubusercontent.com/assets/12489133/13804498/0619b62c-eb80-11e5-88cd-1f876a37aea5.jpg)

**Comment by duongnv1989** [comment]
Logic như sau:
- Nếu dòng đầu tiên là dòng tiêu đề, thì dữ liệu sẽ tính từ dòng sau tiêu đề (thường là bắt đầu dòng thứ hai trong excel) nhưng thực chất là tính từ một sau tiêu đề
- Nếu dòng đầu tiên không phải dòng tiêu đề, thì dữ liệu bắt đầu từ dòng đầu tiên. Trường hợp này thì dòng bắt đầu dữ liệu và dòng trong file excel là tương đương nhau
